### ISSUE TITLE
Undo/Redo : list of undoable/redoable actions

### ISSUE THREAD

**Issue by nicolasaunai** [SciQLop/tscat_gui#49]
The undo/redo icon could allow the user to see a list of actions that can be undone or redone.

**Comment by pboettch** [comment]
Implement a QUndoStack-Widget: 0,5 day once agreed on the style

**Comment by jeandet** [comment]
It could look like this:

![Image](https://user-images.githubusercontent.com/7570249/213485998-9930adcd-e558-4ab0-87ca-3d7861ad8a66.png)

If the menu can remain open after user select that's better!
