### ISSUE TITLE
selecting a catalog after selecting an event from that catalog

### ISSUE THREAD

**Issue by nicolasaunai** [SciQLop/tscat_gui#53]
selecting a catalog shows its properties
selecting an event from that catalog shows the event properties
re-selecting the (same) catalog leaves the properties of the event whereas it should show again those of the catalog
selecting another catalog, however, shows the properties of that catalog OK.

**Comment by nicolasaunai** [comment]
I think at some point we said that selecting an event in a selected catalog should change the "selection color" of the catalog from blue to something like gray. Inversely, re-selecting the catalog after selecting an event in it, should put the selection background color of the event to gray as well.

**Comment by pboettch** [comment]
Does it work for you, the color-change of the catalogue when an event is selected?

Having a catalogue highlight while an event is selected makes sense : this is the currently selected catalogue for this event, but what does a highlighted color  mean for the event if its catalogue is reselected?
