### ISSUE TITLE
manipulating graphically large catalogs (100k) is tedious

### ISSUE THREAD

**Issue by nicolasaunai** [SciQLop/tscat_gui#55]
- clicking on the catalog first takes several seconds to load all the events and display them before the catalog appears to be selected graphically, which gives an awkward feeling something is wrong
- selecting several catalogs one after the other either by clicking or via the arrow key is not fluid at all if one or several large catalogs are selected since each of them blocks the interface for several seconds before other selections are processed.

**Comment by pboettch** [comment]
3 days: rework model and add threaded loading of events (or interval loading). This will significantly improved user experience in the GUI.
