### ISSUE TITLE
Export/import formats

### ISSUE THREAD

**Issue by nicolasaunai** [SciQLop/tscat_gui#60]
today tscat only allows export to JSON.
exporting in other formats such as VOTable could be useful

**Comment by pboettch** [comment]
VOTable, this is an action for tscat. I don't know the format. Is it this one http://www.star.bris.ac.uk/~mbt/topcat/sun253/inVotable.html ?

Need to understand the structure, write the import/export code in tscat and integrate in tscat_gui: 2 days

**Comment by jeandet** [comment]
Yes but you will use this https://docs.astropy.org/en/stable/io/votable/index.html

**Comment by pboettch** [comment]
I think even with a library supporting the serialization, it will still take time to get familiar with and to use it correctly. 

For me, 2 days is a careful estimate.

**Comment by jeandet** [comment]
the best is to first focus on AMDA compatibility, and create some catalogs from AMDA -> export them as VOTable -> use astropy to import it into tscat -> then export it again from tscat with astropy -> then import it from AMDA and check that nothing broke.
