### ISSUE TITLE
show catalog "meta data" 

### ISSUE THREAD

**Issue by nicolasaunai** [SciQLop/tscat_gui#63]
users want to know some information about catalogs such as the number of events, the min start and max start dates, missions concerned if any given in attributes, etc. (TBD)

these info should be accessible in several ways:

- as a contextual info when the on focus
- in the property panel in some section named like "metadata"
- the number of events could appear on the right of the catalog name or at the end of the line

**Comment by pboettch** [comment]
Display meta-data in a TabWidget in the editor-section maybe.
How does the user select which meta-data and statistic is to be shown?

Implementing an extendable Widget showing at least some of the values: 1 day

**Comment by jeandet** [comment]
```Python

meta_data = 
{
    "events count" : my_function,
     "Global start/stop" : my_function2,
}
def my_function(catalog:TBC)-> str or List[str] or...  # -> compatible avec les widgets de la vue.
```
