### ISSUE TITLE
drag and drop

### ISSUE THREAD

**Issue by nicolasaunai** [SciQLop/tscat_gui#64]
- events should be movable with drag and drop, for instance to move or copy them into a catalog
- catalog should be movable with D&D too

**Comment by pboettch** [comment]
Catalogues in the catalogue-view are sorted by alphabet, what would you expected if catalogues are moved within this view?

**Comment by pboettch** [comment]
events D&D, to move/copy to another catalogue: 0,5 days
move catalogues, to be clarified what is required
