### ISSUE TITLE
event rating

### ISSUE THREAD

**Issue by nicolasaunai** [SciQLop/tscat_gui#66]
since signatures in the data motivating the creation of an event of some kind are highly variable, it is often useful to set some kind of quality rating to an event. Like 0 means "I select it but it's far from the textbook signature, I'm unsure this is XXX" and 10 "textbook like signature, I'm 100% confident this is XXXX".

Selecting events based on their rating, via for example the dynamic filter, allows the user to perform statistics on a more or less conservative approach.

Rating could be for instance represented as 5 stars to check as an additional column in the event list.

**Comment by pboettch** [comment]
2 days with testing and user feedback before and after implementation.

**Comment by nicolasaunai** [comment]
cursor, step 1, between 1 and 10, default NaN, fixed attribute

**Comment by pboettch** [comment]
Field is an Optional[int] and in SQL INT NULL. Accepted Value 1-10. 

Slider for editing (0 - no rating, 1 - 10 otherwise), Ticklabels, Label with current Value
Event List Rating Widget - Filled Progess Bar
