### ISSUE TITLE
filtered events and manually added events should appear differently

### ISSUE THREAD

**Issue by nicolasaunai** [SciQLop/tscat_gui#67]
events can be associated with a dynamic catalog for two reasons:
- because it satisfy the selection predicate applied on the whole database
- because it's been manually assigned to this catalog.

when displaying such a catalog it is not obvious anymore which event belong to which category and so what to expect when changing the filter. 

A solution could be to represent events originating from a filter and those from manual assignment differently. Could be a color (maybe a little too much) or a little icon in a column to indicate its origin.

**Comment by pboettch** [comment]
0,5 days, required changes in tscat

**Comment by pboettch** [comment]
There are different ways of how to implement this, need discussion.

- two queries one with predicate, one without and merge the results (will be long if lots of events)
- then how to handle in the GUI an event which is added to a catalogue which was before a predicate event. TSCAT-GUI has to change this information then.

**Comment by pboettch** [comment]
Additional column to display difference.
