### ISSUE TITLE
bulk selection

### ISSUE THREAD

**Issue by nicolasaunai** [SciQLop/tscat_gui#68]
it should be possible to bulk edit events or catalog and perform operations on them.
Two operations at least:
- move/copy them somewhere (export, trash, catalog, etc.)
- edit parameters in the property panel

bulk selection of different objects in nature such as catalog AND events could in principle be possible if there is an intersection in their property to edit, but not part of this issue.

**Comment by pboettch** [comment]
Multiple tasks here, based on multiple selections.

Only catalogues, or only events can be multiple selected.

What happens to event view, when multiple catalogues are selected? Deactivated?

1) bulk-editing, complete overhaul of the edit-widget, 2 days
2) bulk-actions, export, trash: 0.25 days
3) bulk-actions, create new catalogue from events in selection: 0.25 days

4) bulk-editing of different objects types: if 1) is done, 0.25 days

**Comment by jeandet** [comment]
"What happens to event view, when multiple catalogues are selected? Deactivated?"
-> shows union of all selected catalogs
