### ISSUE TITLE
TSCAT database migration with alembic

### ISSUE THREAD

**Issue by pboettch** [SciQLop/tscat_gui#87]

**Comment by jeandet** [comment]
@pboettch do we backup the db before migration? If not, maybe we should do a simple CP before any migration.

**Comment by pboettch** [comment]
No backup. In general a backup before each save with several copies might be a nice idea, no?

**Comment by jeandet** [comment]
Without doing it for each save, I would say that we can copy the db file before each migration with a name like `backend.sqlite.pre-migration-backup-{datetime.now().isoformat}` .
